# Generated by Django 4.2.1 on 2023-06-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='time',
            field=models.IntegerField(default=80),
        ),
    ]
