# Generated by Django 4.2.1 on 2023-06-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0004_course_created_course_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.FloatField(db_index=True),
        ),
    ]
