# Generated by Django 4.2.1 on 2023-06-21 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_alter_course_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
