# Generated by Django 4.2.1 on 2023-06-21 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_alter_course_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
