# Generated by Django 4.2.1 on 2023-06-21 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0010_alter_teacher_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='first.teacher'),
            preserve_default=False,
        ),
    ]
