# Generated by Django 4.2.1 on 2023-06-21 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0011_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coordinator',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='coordinator', to='first.teacher'),
            preserve_default=False,
        ),
    ]
